apiVersion: v1
kind: Service
metadata:
  labels:
    run: splunkenterprise
  name: splunkenterprisesvc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30800
    name: webaccess
  - port: 8089
    protocol: TCP
    targetPort: 8089
    nodePort: 30089
    name: searchindex
  - port: 9997
    protocol: TCP
    targetPort: 9997
    nodePort: 30997
    name: searchheader
  - port: 8008
    protocol: TCP
    targetPort: 8008
    nodePort: 30008
    name: searchindexer2
  selector:
    run: splunkenterprise
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunkenterprise
spec:
  selector:
    matchLabels:
      run: splunkenterprise
  replicas: 4
  template:
    metadata:
      labels:
        run: splunkenterprise
    spec:
      containers:
      - env:
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_PASSWORD
          value: splunk1234
        image: splunk/splunk:latest
        name: splunkenterprise
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: web-access
        - containerPort: 8089
          name: searchindex
        - containerPort: 8008
          name: searchindex2
        - containerPort: 9997
          name: indexerinteg
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
